import { SensorData } from '../types/sensor';

export const sampleSensorData: SensorData[] = [
  {
    id: 5,
    customerName: "Yash Pakka",
    sensorAssigned: "Sensor 2",
    deploymentDate: "28 Sep 23",
    status: "Live",
    latestUpdates: "19-08-25: Sensor data non-continuous and constant at ~630ppm because sampling wasn't started till this date as sampling pipeline was under maintenance.\n26-07-25 : Both the sensors are offline\n05-07-25 : Haber Sensor continuously hitting saturation. (~630ppm)\n16-06-25 : Pi offline. Plant is on annual maintenance till 05-07-25.\n22-05-25 : Network and PLC connectivity issues\n-------------------------------------------------------------\nLab data received\nLab data is pending",
    reasonForTrouble: "",
    resolutionStatus: "",
    deployment: "Deployed",
    unit: "PM3",
    application: "RDA",
    parameter: "TSS",
    measurementRange: "400-3000 ppm"
  },
  {
    id: 6,
    customerName: "Jani Sales",
    sensorAssigned: "Sensor 6",
    deploymentDate: "29 Dec 24",
    status: "Live",
    latestUpdates: "05-08-25 : Sudden spike in Ref. TSS sensor at 15:16 (was due to cal)\n01-08-25 : Plant shutdown from 04:00 till 04-08-25 evening\n29-07-25 : Calibration fixed at 12:00\n04-07-25 : Plant shutdown from 04-07-25 00:00 till 05-07-25\n26-06-25 : New ML model loaded.\n09-05-25 : Plant is live. Data is getting logged into dashboard and AWS\n<Need to put a model. Check if it predicts well for the last 10 days>\n------------------------------------------------------------------------\nGrade change. A sticky substance is sticking on the sensor head. Cleaning happens everyday. However, it goes to saturation after ~2h of cleaning. Single point calibration happened 24-04-25. However, we are having an internet issue.",
    reasonForTrouble: "",
    resolutionStatus: "",
    deployment: "Deployed",
    unit: "PM",
    application: "RDA",
    parameter: "TSS",
    measurementRange: ""
  },
  {
    id: 7,
    customerName: "Pudumjee",
    sensorAssigned: "Sensor 8",
    deploymentDate: "18 Feb 25",
    status: "Trouble",
    latestUpdates: "18-08-25 : (8:00) Both sensor Data not reflecting on dashboard\n23-07-25 : Plant was off till 25-07-25 13:00\nTransmitter is locked. Values shown are out of range.\n25-02-25 : Values started to come in.",
    reasonForTrouble: "Possibly network issues since data not receiving to the cloud",
    resolutionStatus: "Asked the site team to check on that",
    deployment: "Deployed",
    unit: "PM1",
    application: "TD",
    parameter: "TSS",
    measurementRange: ""
  },
  {
    id: 9,
    customerName: "ITC Bhadrachalam",
    sensorAssigned: "Sensor 3",
    deploymentDate: "21 Mar 25",
    status: "Live",
    latestUpdates: "06-08-25: (21:00) Sensor data not reflecting due to TSS RPi network failures causing uploading issues.\n15-07-25: Sensor data not reflecting on dashboard\n26-05-25 : Sensor continuously hitting saturation. Network issues.\n<Kalyan needs to visit the plant to implement a solution (delay of ~5 min to clear the clogging) for the saturation issue>\n---------------------------------------------------------------------\nThere are 3 layers of TSS (10K ppm ; 7K ppm ; 500ppm )\nBackwater realtime is the best match to Haber TSS Sensor.\nHowever, 10K ppm hits saturation for Hach TSS Sensor.\nTransmitter ranges needs to be changed.",
    reasonForTrouble: "Frequent Network disconnections since a single Wifi network is shared between 3 different RPi devices",
    resolutionStatus: "Sent 3 Ethernet cables to the site (no update till now)",
    deployment: "Deployed",
    unit: "PM1A",
    application: "RDA",
    parameter: "TSS",
    measurementRange: ""
  },
  {
    id: 10,
    customerName: "Kuantum Papers Ltd.",
    sensorAssigned: "Sensor 5",
    deploymentDate: "23 May 25",
    status: "Trouble",
    latestUpdates: "19-08-25: (12:00) Data constant at 1.43 NTU on dashboard.\n26-06-25 : Data is getting logged into dashboard\n25-05-25 : Connection issue. The team is able to ping eLIXA and PLC but not the TSS Sensor.\n<Update on sensor moved to century>",
    reasonForTrouble: "RPi disconnected",
    resolutionStatus: "Contact any site person to troubleshoot the issue",
    deployment: "Deployed",
    unit: "RWP",
    application: "CWT",
    parameter: "TRB",
    measurementRange: ""
  },
  {
    id: 11,
    customerName: "Century",
    sensorAssigned: "Sensor 14",
    deploymentDate: "24 Jul 25",
    status: "Live",
    latestUpdates: "18-08-25 (10:00) - 19-08-25 (14:00): No data since sim cards were not configured through the wifi router causing no network connection for the time being\n02-08-25: Rate and offset was changed to display the correct range, therefore, Haber TSS readings show 10x times of Backwater reading\n24-07-25: Readings started 11:17 onwards",
    reasonForTrouble: "",
    resolutionStatus: "",
    deployment: "Deployed",
    unit: "PM3",
    application: "RDA",
    parameter: "TSS",
    measurementRange: "900-1100 ppm"
  },
  {
    id: 12,
    customerName: "Century",
    sensorAssigned: "Sensor 13",
    deploymentDate: "",
    status: "NA",
    latestUpdates: "",
    reasonForTrouble: "Not Deployed yet.",
    resolutionStatus: "",
    deployment: "To be deployed",
    unit: "BM6",
    application: "RDA",
    parameter: "",
    measurementRange: ""
  }
];